### ISSUE TITLE
dynamic is not a subtype of type 'Parser'

### ISSUE THREAD

**Issue by RedTo** [polux/parsers#22]
Since I updated flutter yesterday I'm always getting this error if I try to execute the [full_arith](https://github.com/polux/parsers/blob/master/example/full_arith.dart) example:
`type '() => dynamic' is not a subtype of type '() => Parser'`

It seems that there has something changed, or am I wrong?

**Comment by RedTo** [comment]
Sorry for the trouble, I was wrong...
Some parts of the dart sdk were still from the old branch, little bit strange but now everything is working!

**Comment by polux** [comment]
Not sure what happened to you but I recently updated a bunch of type signatures in the library to make it strong mode compliant, then I bumped the version number to 1.0.0. So maybe you updated the lib to 1.0.0 but not the SDK? I've remarked while updating my libs to strong mode that as the SDK version increase, they discover more strong mode errors.
